// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC6EE2bGa5lA1_maRv-h7Eh7ztgeNG8a4E',
    appId: '1:1060653087221:android:de2c2c1804a1abcb74c8bc',
    messagingSenderId: '1060653087221',
    projectId: 'ur-place-8f54c',
    storageBucket: 'ur-place-8f54c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB5aOu8Kl-cuQNm5r2ZykS7wdiC4aa0nkQ',
    appId: '1:1060653087221:ios:d88ec4dd6878bde874c8bc',
    messagingSenderId: '1060653087221',
    projectId: 'ur-place-8f54c',
    storageBucket: 'ur-place-8f54c.appspot.com',
    iosBundleId: 'com.aleksicbraun.urPlace',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB5aOu8Kl-cuQNm5r2ZykS7wdiC4aa0nkQ',
    appId: '1:1060653087221:ios:d88ec4dd6878bde874c8bc',
    messagingSenderId: '1060653087221',
    projectId: 'ur-place-8f54c',
    storageBucket: 'ur-place-8f54c.appspot.com',
    iosBundleId: 'com.aleksicbraun.urPlace',
  );
}
